### PR TITLE
Briefly update README.md

### LINKED ISSUE #82: README.md 다시 쓰기
너무 오래되었습니다.

* `npm`으로 `yarn`을 설치하는 건 별로 좋지 않습니다(제가 적었지만). 스크립트로 홈 디렉토리에 설치해 쓰는 방법이 좋을 것 같군요.
* 이 프로젝트의 간단한 설명도 필요할 것 같습니다.

### PR DESCRIPTION
**Pull request by simnalamburt**
This PR closes #82. Please review and merge it by yourself!

**[Click to see rendered README.md](https://github.com/simnalamburt/www.snucse.org/blob/readme/README.md#readme)**

### CODE REVIEW

**Review by tirr-c — CHANGES_REQUESTED** [review]
Please write this also in Korean. Most of SNUCSE users are Korean, and we can't ignore them.

**Comment by simnalamburt** [comment]
@VBChunguk Alright, but I won't translate the license term as Free Software Foundation advise.

**Comment by simnalamburt** [comment]
@VBChunguk Is there any update need to be done?

P.S. Please check https://github.com/snucse/snucse-api/pull/4 too.

**Review by tirr-c — APPROVED** [review]
I think English `README.md` and Korean `README.ko.md` is okay; how do you think? @snucse/snucse

**Pull request merged**
